export const team = [
  {
    name: "Abdelrahman Ezzat",
    title: "Founder & Supervisor",
    role: "High Board",
    facebook: "https://www.facebook.com/abdelrahmanezzat00",
    linked: "https://www.linkedin.com/in/abdelrahman-ezzat-502454247",
    gmail: "ezzatabdelrahman41@gmail.com",
    img: "/AbdelrahmanEzzat.jpg",
  },
  {
    name: "Hamss Mohsen",
    title: "General Director",
    role: "High Board",
    facebook:
      "https://www.facebook.com/profile.php?id=100004206315121&mibextid=LQQJ4d",
    linked: "https://www.linkedin.com/in/hamss-mohsen-223241235",
    gmail: "hamssmohsen222@gmail.com",
    img: "/HamssMohsen.jpg",
  },
  {
    name: "Gohar Hany",
    title: "Project Manager",
    role: "High Board",
    facebook: "https://www.facebook.com/gohar.hany",
    linked: "https://www.linkedin.com/in/gohar-hany-764697256/",
    gmail: "goharhany9@gmail.com",
    img: "/Gohar.jpeg",
  },
  {
    name: "Momen Saad",
    title: "Project Manager",
    role: "High Board",
    facebook: "https://www.facebook.com/xmuuka/",
    linked: "https://www.linkedin.com/in/moamenshamed/",
    gmail: "moamenxking@gmail.com",
    img: "/MomenSaad.jpg",
  },
  {
    name: "Somaya Saeed",
    title: "Project Manager",
    role: "High Board",
    facebook: "",
    linked: "",
    gmail: "",
    img: "/SomayaSaeed.jpg",
  },
  {
    name: "Mahmoud Saeed",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "https://www.facebook.com/mahmoud.saied.7587370",
    linked: "https://www.linkedin.com/in/mahmoud-saeed-916917282",
    gmail: "hodaelgentle@gmail.com",
    img: "/MahmoudSaeed.jpg",
  },

  {
    name: "Ahmed Samy",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "https://www.facebook.com/Samyy2002",
    linked: "https://www.linkedin.com/in/ahmed-samy2002",
    gmail: "asamy8087@gmail.com",
    img: "/AhmedSamy.jpg",
  },
  {
    name: "Ahmed Ashraf",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "https://www.facebook.com/profile.php?id=100017815245514",
    linked: "",
    gmail: "",
    img: "/AhmedAshraf.jpg",
  },
  {
    name: "Ahmed Yasser",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook:
      "https://www.facebook.com/profile.php?id=100012905670502&mibextid=ZbWKwL",
    linked: "https://www.linkedin.com/in/ahmed-yasser-7baab4222",
    gmail: "ahmedyasser100029@gmail.com",
    img: "/AhmedYasser.jpg",
  },
  {
    name: "Abdallah Abdelrahman",
    title: "PR Sector Board",
    role: "Public Relations",
    facebook:
      "https://www.facebook.com/profile.php?id=100008853287496&mibextid=ZbWKwL",
    linked: "https://www.linkedin.com/in/abdallah-abdelrahman-185771250",
    gmail: "abdallahabdelrahman212@gmail.com",
    img: "/AbdallahAbdelrahman.jpg",
  },
  {
    name: "Habiba Ayman",
    title: "PR Sector Board",
    role: "Public Relations",
    facebook: "https://www.facebook.com/profile.php?id=100009274807332",
    linked: "https://www.linkedin.com/in/habiba-ayman-2614a1289",
    gmail: "habobaaa456@gmail.com",
    img: "/HabibaAiman.jpg",
  },
  {
    name: "Basmallah Ahmed",
    title: "HR Sector Board",
    role: "Human Resources",
    facebook: "https://www.facebook.com/basmallah.ahmed.31?mibextid=ZbWKwL",
    linked:
      "https://www.linkedin.com/in/basmalla-mohamed-18b4941b7?trk=contact-info",
    gmail: "basmallabu@gmail.com",
    img: "/BasmallahAhmed.jpg",
  },
  {
    name: "Radwa Mohamed",
    title: "HR Sector Board",
    role: "Human Resources",
    facebook:
      "https://www.facebook.com/profile.php?id=100092475640673&mibextid=ZbWKwL",
    linked: "https://www.linkedin.com/in/radwa-mohamed-160403220",
    gmail: "radwa555ff@gmail.com",
    img: "/RadwaMohamed.jpg",
  },
  {
    name: "Fares Atef",
    title: "HR Sector Board",
    role: "Human Resources",
    facebook:
      "https://www.facebook.com/profile.php?id=100003538764954&mibextid=ZbWKwL",
    linked: "https://www.linkedin.com/in/fares-atef-524b66255",
    gmail: "faresatef21@gmail.com",
    img: "/FareAtef.jpg",
  },
  {
    name: "Salma Elhawy",
    title: "CB Sector Board",
    role: "Capacity Building",
    facebook: "https://www.facebook.com/salma.essam.12?mibextid=ZbWKwL",
    linked: "https://www.linkedin.com/in/salma-essam-b2b463241",
    gmail: "salmaelhewy@gmail.com",
    img: "/SalmaElhawy.jpg",
  },
  {
    name: "Mai Kadry",
    title: "CB Sector Board",
    role: "Capacity Building",
    facebook: "https://www.facebook.com/may.kadry.12?mibextid=ZbWKwL",
    linked: "https://www.linkedin.com/in/mai-kadry-292789286",
    gmail: "kadrymai3@gmail.com",
    img: "/MaiKadry.jpg",
  },
  {
    name: "Omar Gaber",
    title: "OC Sector Board",
    role: "Organization",
    facebook: "https://www.facebook.com/profile.php?id=100008392236180",
    linked: "https://www.linkedin.com/in/omar-gaber-7894a0286",
    gmail: "omargaber783@gmail.com",
    img: "/OmarGaber.jpg",
  },
  {
    name: "Mohamed Hassan",
    title: "OC Sector Board",
    role: "Organization",
    facebook: "https://www.facebook.com/z8oby",
    linked: "https://www.linkedin.com/in/mohamed-hassan-273787286/",
    gmail: "mohamedhassan30304@gmail.com",
    img: "/MohamedHassan.jpg",
  },
  {
    name: "Azza Emad",
    title: "OC Sector Board",
    role: "Organization",
    facebook: "https://www.facebook.com/azza.emad.315",
    linked: "https://www.linkedin.com/in/azza-emad-568893255",
    gmail: "ba8260026@gmail.com",
    img: "/AzzaEmad.jpg",
  },
  {
    name: "Govany Wagdy",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook: "https://www.facebook.com/govaney.wagdy.9",
    linked: "https://www.linkedin.com/in/govaney-wagdy-49abb8280",
    gmail: "Govaney77@gmail.com",
    img: "/GovanyWagdy.jpg",
  },
  {
    name: "Mohamed Saeed",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook: "https://www.facebook.com/mosaeed6",
    linked: "https://www.linkedin.com/in/mohamed-saeed-40a7b2191",
    gmail: "Mohsaeed1235@gmail.com",
    img: "/MohamedSaeed.jpg",
  },
  {
    name: "Ammar Mohamed",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook:
      "https://m.facebook.com/profile.php/?id=100011303200287&name=xhp_nt__fb__action__open_user",
    linked: "https://www.linkedin.com/in/ammar-rekaby-67248a243/",
    gmail: "rekaby14@gmail.com",
    img: "/AmmarMohamed.png",
  },
  {
    name: "Simon Nabil",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook: "https://www.facebook.com/simon.nabil.58?mibextid=ZbWKwL",
    linked:
      "https://www.linkedin.com/in/simon-nabil-713b89256?trk=contact-info",
    gmail: "simonnabil2255@gmail.com",
    img: "/SimonNabil.jpg",
  },
  {
    name: "Mahmoud Naser",
    title: "CC Sector Board",
    role: "Content Creator",
    facebook:
      "https://www.facebook.com/profile.php?id=100048838802583&mibextid=ZbWKwL",
    linked: "https://www.linkedin.com/in/mahmoud-nasr-71166021a",
    gmail: "01157072035m@gmail.com",
    img: "/MahmoudNaser.jpg",
  },
  {
    name: "Manar Mohamed",
    title: "CC Sector Board",
    role: "Content Creator",
    facebook:
      "https://www.facebook.com/profile.php?id=100009651768689&mibextid=9R9pXO",
    linked: "https://www.linkedin.com/in/manar-sedira-3005a9255",
    gmail: "manarsedo@gmail.com",
    img: "/ManarMohamed.jpg",
  },
];

export const nav = {
  admin: [
    { title: "Courses", path: "" },
    { title: "Add New Course", path: "/addcourse" },
    { title: "Users", path: "/users" },
    { title: "Add New User", path: "/adduser" },
    { title: "Messages", path: "/messages" },
    { title: "Table", path: "/table" },
  ],
  subAdmin: [
    { title: "Courses", path: "" },
    { title: "Add New Course", path: "/addcourse" },
    { title: "Users", path: "/users" },
  ],
};
