export const team = [
  {
    name: "Abdelrahman Ezzat",
    title: "Founder & Supervisor",
    role: "High Board",
    facebook: "https://www.facebook.com/abdelrahmanezzat00",
    insta: "https://www.instagram.com/abd_elrahman__ezzat/",
    whats: "https://wa.me/+201211477606",
    img: "/AbdelrahmanEzzat.jpg",
  },
  {
    name: "Hamss Mohsen",
    title: "General Director",
    role: "High Board",
    facebook: "",
    insta: "",
    whats: "",
    img: "/HamssMohsen.jpg",
  },
  {
    name: "Gohar Hany",
    title: "Project Manager",
    role: "High Board",
    facebook: "https://www.facebook.com/gohar.hany",
    insta: "https://www.instagram.com/gohar_hany/",
    whats: "https://wa.me/+201284709314",
    img: "/Gohar.jpeg",
  },
  {
    name: "Momen Saad",
    title: "Project Manager",
    role: "High Board",
    facebook: "https://www.facebook.com/abdelrahmanezzat00",
    insta: "https://www.instagram.com/abd_elrahman__ezzat/",
    whats: "https://wa.me/+201211477606",
    img: "/MomenSaad.jpg",
  },
  {
    name: "Somaya Saeed",
    title: "Project Manager",
    role: "High Board",
    facebook: "https://www.facebook.com/abdelrahmanezzat00",
    insta: "https://www.instagram.com/abd_elrahman__ezzat/",
    whats: "https://wa.me/+201211477606",
    img: "/SomayaSaeed.jpg",
  },
  {
    name: "Mahmoud Saeed",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "https://www.facebook.com/mahmoud.saied.7587370",
    insta: "https://www.instagram.com/el.forma/",
    whats: "https://wa.me/+201224884609",
    img: "/MahmoudSaeed.jpg",
  },
  {
    name: "Yara Mohamed",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "",
    insta: "",
    whats: "",
    img: "/YaraMohamed.jpg",
  },
  {
    name: "Ahmed Samy",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "https://www.facebook.com/Samyy2002",
    insta: "https://www.instagram.com/a_samy_i/",
    whats: "https://wa.me/+201503934529",
    img: "/AhmedSamy.jpg",
  },
  {
    name: "Ahmed Ashraf",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "https://www.facebook.com/profile.php?id=100017815245514",
    insta: "https://www.instagram.com/aahmeddashraf_/",
    whats: "https://wa.me/+201211601288",
    img: "/AhmedAshraf.jpg",
  },
  {
    name: "Ahmed Yasser",
    title: "Instructor Technical Sector",
    role: "Technical",
    facebook: "",
    insta: "",
    whats: "",
    img: "/AhmedYasser.jpg",
  },
  {
    name: "Abdallah Abdelrahman",
    title: "PR Sector Board",
    role: "Public Relations",
    facebook: "https://www.facebook.com/profile.php?id=100008853287496",
    insta: "https://www.instagram.com/abdallah_abdelrahman212/",
    whats: "https://wa.me/+201212206828",
    img: "/AbdallahAbdelrahman.jpg",
  },
  {
    name: "Habiba Ayman",
    title: "PR Sector Board",
    role: "Public Relations",
    facebook: "",
    insta: "",
    whats: "",
    img: "/HabibaAyman.jpg",
  },
  {
    name: "Basmallah Ahmed",
    title: "HR Sector Board",
    role: "Human Resources",
    facebook: "",
    insta: "",
    whats: "",
    img: "/BasmallahAhmed.jpg",
  },
  {
    name: "Radwa Mohamed",
    title: "HR Sector Board",
    role: "Human Resources",
    facebook: "",
    insta: "",
    whats: "",
    img: "/RadwaMohamed.jpg",
  },
  {
    name: "Fares Atef",
    title: "HR Sector Board",
    role: "Human Resources",
    facebook: "https://www.facebook.com/profile.php?id=100003538764954",
    insta: "https://www.instagram.com/fares_atef7/",
    whats: "https://wa.me/+201153462865",
    img: "/FareAtef.jpg",
  },
  {
    name: "Salma Elhawy",
    title: "CB Sector Board",
    role: "Capacity Building",
    facebook: "",
    insta: "",
    whats: "",
    img: "/SalmaElhawy.jpg",
  },
  {
    name: "Mai Kadry",
    title: "CB Sector Board",
    role: "Capacity Building",
    facebook: "",
    insta: "",
    whats: "",
    img: "/MaiKadry.jpg",
  },
  {
    name: "Omar Gaber",
    title: "OC Sector Board",
    role: "Organization",
    facebook: "https://www.facebook.com/profile.php?id=100008392236180",
    insta: "https://www.instagram.com/omar_gaber_23/",
    whats: "https://wa.me/+201280405565",
    img: "/OmarGaber.jpg",
  },
  {
    name: "Mohamed Hassan",
    title: "OC Sector Board",
    role: "Organization",
    facebook: "https://www.facebook.com/z8oby",
    insta: "https://www.instagram.com/mohamedhassan30304/",
    whats: "https://wa.me/+201270708266",
    img: "/MohamedHassan.jpg",
  },
  {
    name: "Azza Emad",
    title: "OC Sector Board",
    role: "Organization",
    facebook: "",
    insta: "",
    whats: "",
    img: "/AzzaEmad.jpg",
  },
  {
    name: "Govany Wagdy",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook: "https://www.facebook.com/govaney.wagdy.9",
    insta: "https://www.instagram.com/govaney_wagdy/",
    whats: "https://wa.me/+201024259796",
    img: "/GovanyWagdy.jpg",
  },
  {
    name: "Mohamed Saeed",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook: "https://www.facebook.com/mosaeed6",
    insta: "https://www.instagram.com/mo_saeed6/",
    whats: "https://wa.me/+201021595385",
    img: "/MohamedSaeed.jpg",
  },
  {
    name: "Ammar Mohamed",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook: "",
    insta: "",
    whats: "",
    img: "/AmmarMohamed.png",
  },
  {
    name: "Simon Nabil",
    title: "Media Sector Board",
    role: "Multi Media",
    facebook: "",
    insta: "",
    whats: "",
    img: "/SimonNabil.jpg",
  },
];

export const nav = {
  admin: [
    { title: "Courses", path: "" },
    { title: "Add New Course", path: "/addcourse" },
    { title: "Users", path: "/users" },
    { title: "Add New User", path: "/adduser" },
    { title: "Messages", path: "/messages" },
    { title: "Table", path: "/table" },
  ],
  subAdmin: [
    { title: "Courses", path: "" },
    { title: "Add New Course", path: "/addcourse" },
    { title: "Users", path: "/users" },
  ],
};
